# Generated by Django 4.2.4 on 2023-09-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('loss', models.CharField(max_length=50)),
                ('profit', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_sell', models.CharField(choices=[('sell', 'sell'), ('buy', 'buy')], max_length=100)),
                ('stock_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.CharField(max_length=100)),
                ('buy_quantity', models.IntegerField(max_length=50)),
                ('sell_quantity', models.IntegerField(max_length=50)),
                ('loss', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('Account_No', models.CharField(max_length=12)),
                ('ifsc', models.CharField(max_length=10)),
                ('panNo', models.CharField(max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
    ]
