# Generated by Django 4.2.4 on 2023-10-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolebased', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerifiaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('otp', models.CharField(max_length=4)),
                ('is_verfied', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhaarCardNumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='bankaccount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='ifsccode',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='pancard',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
