# Generated by Django 3.2.8 on 2023-09-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincontact',
            old_name='age',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='maincontact',
            old_name='city',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='maincontact',
            old_name='country',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='maincontact',
            old_name='name',
            new_name='phone',
        ),
    ]
