# Generated by Django 4.2.4 on 2023-09-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230918_2049'),
    ]

    operations = [
    ]
