# Generated by Django 4.2.4 on 2023-09-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230926_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincontact',
            name='phone',
        ),
        migrations.AddField(
            model_name='maincontact',
            name='message',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='maincontact',
            name='subject',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
